config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :registrations
  devise_for :staffs, controllers: { confirmations: 'staffs/confirmations', registrations: 'staffs/registrations' }
  devise_for :customers, controllers: { confirmations: 'customers/confirmations', registrations: 'customers/registrations' }

  devise_scope :staff do
    patch "/staffs/confirm" => "staffs/confirmations#confirm", :as => :staff_confirm
  end

  root 'home#welcome'

  get 'customers/home' => 'customers#home'

  get 'staffs/home' => 'staffs#home'

  resources :customers, only: :update
  namespace :customers do
    get 'availabilities' => 'availabilities#index'
    get 'active_appointments' => 'appointments#active_appointments'
    get 'appointment_history' => 'base#appointment_history'
    get 'active_appointments_index' => 'base#active_appointments_index'
    get 'inactive_appointments_index' => 'base#inactive_appointments_index'
    get 'past_appointments' => 'appointments#past_appointments'
    get 'reminder_settings' => 'base#reminder'
    resources :appointments do
      patch 'cancel' => 'appointments#cancel', on: :member
    end
  end


  namespace :staffs do
    resources :appointments
    get 'active_appointments' => 'appointments#active_appointments'
    get 'past_appointments' => 'appointments#past_appointments'
  end

  namespace :admin do
    resources :staffs
    patch 'staff_resend_confirmation_mail' => 'staffs#resend_confirmation_mail'
    resources :appointments do
      get 'search' => 'appointments#index', on: :collection
      patch 'cancel' => 'appointments#cancel', on: :member
    end
    get 'active_appointments' => 'appointments#active_appointments'
    get 'past_appointments' => 'appointments#past_appointments'
    resources :services, except: :destroy
    resources :availabilities, except: :destroy
    resources :customers, except: [:new, :create]
    resources :application_images, only: :index
    resources :logos, only: [:new, :create, :edit, :update, :destroy]
    resources :backgrounds, only: [:new, :create, :edit, :update, :destroy]
    get '/' => 'base#home'
  end

  resources :staffs, except: [:new, :create, :index], constraints: {id: /[0-9]+/} do
    patch 'update_password' => 'staffs#update_password', on: :member
  end

  get 'services/search' => 'services#search'
  match '*other', :to => redirect('/404.html'), via: [:get]
end

app/models/service.rb
class Service < Db1

  ALLOWED_DURATIONS = [15, 30, 45, 60]

  #validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :duration, inclusion: { in: ALLOWED_DURATIONS }
  validates :enabled, exclusion: { in: [nil] }

  # [rai] what!!!!....really. can't we just add presence validation for enabled. a boolean could have only nil, true or false(fixed)

  #associations
  has_many :allocations, dependent: :restrict_with_error
  has_many :staffs, through: :allocations
  has_many :availability_services
  has_many :availabilities, through: :availability_services
  has_many :available_staff, through: :availabilities, source: 'Staff', foreign_key: 'staff_id'
  has_many :appointments
  has_many :appointed_staffs, through: :appointments, source: 'Staff', foreign_key: 'staff_id'
  has_many :appointed_customers, through: :appointments, source: 'Customer', foreign_key: 'customer_id'

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController

  before_action :load_service, only: [:show, :edit, :update]

  def index
    if params[:enabled].blank?
      @services = Service.order("LOWER(name)").page(params[:page]).per(15)
    else
      @services = Service.where(enabled: params[:enabled]).order("LOWER(name)").page(params[:page]).per(15)
    end
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to admin_service_path(@service),
        notice: 'Service was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @service.update(service_params)
      redirect_to admin_service_path(@service),
        notice: 'Service was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    def load_service
      unless @service = Service.find_by(id: params[:id])
        redirect_to admin_services_path, alert: 'No service found.'
      end
    end

    def service_params
      params.require(:service).permit(:name, :duration, :enabled)
    end
end

app/controllers/admins/services_controller.rb
class Admins::ServicesController < ApplicationController

  before_action :set_service, only: [:show, :edit, :update]
  before_action :check_admin_logged_in, only: [:index, :show, :new, :edit, :create, :update]

  layout 'admin'

  def index
    @services = Service.order(:name)
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to @service,
        notice: 'Service was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @service.update(service_params)
      redirect_to @service,
        notice: 'Service was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def search
    @services = Service.where("name like '#{ params[:q] }%'")
    render json: @services
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service
    unless @service = Service.find_by(id: params[:id])
      flash[:notice] = 'No service found.'
      redirect_to services_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def service_params
    params.require(:service).permit(:name, :duration, :enabled)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def get_duration_periods
    Service::ALLOWED_DURATIONS.map do |duration_period|
      ["#{ duration_period } min", duration_period]
    end
  end
end

app/views/admin/services/_form.html.erb
<div class='errors'>
  <% @service.errors.full_messages.each do |message| %>
    <p> <%= message %> </p>
  <% end %>
</div>
<%= form_for([:admin, @service], html: { class: "form-horizontal" }) do |f| %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>*
    <div class="controls">
      <%= f.text_field :name %>
    </div>
    <%= error_span(@service[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :duration, :class => 'control-label' %>*
    <div class="controls">
      <%= f.select :duration, options_for_select(get_duration_periods, @service.duration), :class => 'form-control' %>
    </div>
    <%= error_span(@service[:duration]) %>
  </div>
  <div class='control-group'>
    <%= f.label :enabled %>
    <span class='control'>
      <%= f.check_box :enabled, checked: true %>
    </span>
  </div><br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

app/views/admin/services/_index.html.erb
<table class = 'table table-hover table-striped'>
  <tr>
    <th>
      Name
    </th>
    <th>
      Duration
    </th>
    <th>
      Enabled
    </th>
    <th>
      Actions
    </th>
  </tr>
  <% @services.each do |service| %>
    <tr class="filter_row <%= service.enabled ? 'enabled' : 'disabled' %>"> 
      <td>
        <%= service.name.titleize %>
      </td>
      <td>
        <%= "#{ service.duration } minutes" %>
      </td>
      <td>
        <%= service.enabled %>
      </td>
      <td>
        <%= link_to 'Show', admin_service_path(service) %>
        |
        <%= link_to 'Edit', edit_admin_service_path(service) %><br/>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @services %>
<br />
<%= link_to 'New service', new_admin_service_path %>

app/views/admin/services/edit.html.erb
<div class='page-header'>
  <h1>Editing service</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', admin_service_path(@service) %> |
<%= link_to 'Back', admin_services_path %>

app/views/admin/services/index.html.erb
<h1>Listing Services</h1>

<%= render '/admin/shared/enabled_filter' %>

<%= link_to 'New service', new_admin_service_path %>
<br />

<div class='row'>
  <div class='col-md-6'>
  </div>
  <div class='col-md-6'>
    <div id='loader_div'>
      <%= image_tag '/loader.gif', height: '25px', width: '25px' %>
    </div>
  </div>
</div>

<div id='list_div'>
  <%= render 'index' %>
</div>

<%= javascript_include_tag 'enabled_filter' %>

app/views/admin/services/index.js.erb
var $listDiv = $('#list_div');

$listDiv.html("<%= escape_javascript(render 'index') %>");

app/views/admin/services/new.html.erb
<div class='page-header'>
  <h1>New service</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', admin_services_path %>

app/views/admin/services/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @service.name.titleize %>
</p>

<p>
  <strong>Duration(Minutes): </strong>
  <%= @service.duration %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @service.enabled? %>
</p>

<%= link_to 'Edit', edit_admin_service_path(@service) %> |
<%= link_to 'Back', admin_services_path %>